### ISSUE TITLE
support isotp_us_to_st_min / isotp_st_min_to_us

### ISSUE THREAD

**Issue by brandonros** [SimonCahill/isotp-c#11]
so that 0xF3 st_min will be 300us instead of rounded up to 1ms

https://github.com/Switchleg1/esp32-isotp-ble-bridge/blob/BridgeLEG/main/isotp.c#L9

this person has it working here

**Comment by SimonCahill** [comment]
That repository is also missing the copyright and licensing notice. Thanks for bringing it to my attention.
