### ISSUE TITLE
Building a static library unnecessarily forces adoption of PIC (position independent code)

### ISSUE THREAD

**Issue by pgreenland** [SimonCahill/isotp-c#25]
Hi,

I'm in the process of integrating isotp-c into a microcontroller project.

We're using CMake so have included the project as a subdirectory setting the isotpc_STATIC_LIBRARY configuration option.

As noted in the project README, position independent code (PIC) is always forced on:

https://github.com/SimonCahill/isotp-c/blob/34fa61ab7268a03788c7d366715331e6ec1bfb7f/CMakeLists.txt#L22

I was hoping to understand the rationale behind this, as it's typically only required for dynamic libraries.

Additionally flagging the target_compile_options as public means they're propagated to dependencies. Causing build options to sort of "leak" out of the library into the modules which link to it.

https://github.com/SimonCahill/isotp-c/blob/34fa61ab7268a03788c7d366715331e6ec1bfb7f/CMakeLists.txt#L21

In our case our startup code doesn't include any support for PIC, as everything is statically linked. I was surprised to find the system crashing at startup, having linked in isotp-c. Seems its compile definitions had spread and attempted to enable PIC on the module which links to the library causing the system to crash as PIC wasn't properly setup.

For the moment I've just commented out the PIC option but was hoping to submit a PR. Either to make it configurable via cmake, or to only include it when requesting a shared library be built.

I'd propose to make the other compile options private, such that they're only applied to the isotp-c library itself. They're not bad in terms of what they're looking to do. We've got everything but -Wno-unknown-pragmas turned on ourselves already, so aside from PIC didn't really notice them. They probably shouldn't be forced upon the wider project as a whole though. 

Would appreciate your thoughts.

Great work on continuing the development of the library btw!

Thanks,

Phil

**Comment by SimonCahill** [comment]
IIRC this is from a weird Debian-based system with an old compiler suite that needed the option to link correctly.
Feel free to submit a PR making this configurable.

> Additionally flagging the target_compile_options as public means they're propagated to dependencies.

This is most definitely an oversight on my end. I hadn't run into any issues with this, so it just got looked over. Again, feel free to create a PR (can be one single PR for these two cases) and I'll merge it.

Thanks for bringing this up! Much appreciated!

> Great work on continuing the development of the library btw!

My pleasure, it's been a super useful library with some of my (and my customers') applications :)

**Comment by pgreenland** [comment]
Thanks for the background!

I figured there was probably a reason.....at the same time found myself googling when might a static library need PIC enabled 🙈.

I've raised https://github.com/SimonCahill/isotp-c/pull/27 - I'm thinking there's a way to reference this issue in the PR, but alas the button alludes me.

**Comment by SimonCahill** [comment]
GitHub is pretty cool in that it scans the text in PRs and comments for phrases like "closes #<issue>".

But I can do that for you too :)
