### ISSUE TITLE
Never executed else if branch in time calculation

### ISSUE THREAD

**Issue by RobertZickler** [SimonCahill/isotp-c#33]
The if condition here https://github.com/SimonCahill/isotp-c/blob/5ddce32e16a21efd1d559ea865730cf32c8727d5/isotp.c#L11 will always be true before the else if branch https://github.com/SimonCahill/isotp-c/blob/5ddce32e16a21efd1d559ea865730cf32c8727d5/isotp.c#L13 could ever become true.

I propose: 

```c
/* st_min to microsecond */
static uint8_t isotp_us_to_st_min(uint32_t us) {
    if (us <= 127000) {
        if (us >= 100 && us <= 900) 
        {
            return 0xF0 + (us / 100);
        } 
        else 
        {
            return us / 1000;
        }
    }
    return 0;
}
```

[Edit:] <s>Same here: https://github.com/SimonCahill/isotp-c/blob/5ddce32e16a21efd1d559ea865730cf32c8727d5/isotp.c#L21-L25</s>

**Comment by SimonCahill** [comment]
You're right. I'll add a fix and reference this issue.

**Comment by SimonCahill** [comment]
> Same here:

Unless I'm not seeing something, this check works as-is. `7f` (127) is less than `f1` (241).

**Comment by RobertZickler** [comment]
Yes, your totally right. The second one is fine. I read the `F` in the wrong position.

**Comment by SimonCahill** [comment]
Then I'll merge the PR tomorrow and create a new tag.

Thanks for contributing!
